language: node_js
node_js:
  - "8"
  - "10"
  - "12"

script: "npm test"

jobs:
  include:
    - language: node_js
      node_js: 6
      script: "node6-test"
    - language: node_js
      node_js: node
      script: "npm test"
      after_success: "npm run coveralls"
